# Regenerate the two .bat launchers so they survive paths containing
# parentheses / ampersands / spaces. cmd.exe aborts with "... was unexpected
# at this time." when %VAR% inside an if(...) block expands to such a path,
# so every check uses if/errorlevel/goto instead of parenthesised blocks.
import pathlib

LAN = [
    "@echo off",
    "setlocal EnableExtensions",
    "rem ===========================================================",
    "rem  WorkBuddy proxy - LAN mode",
    "rem",
    "rem  Listens on every network interface so phones, laptops and",
    "rem  other PCs on the same network can use it.",
    "rem",
    "rem  An API key is REQUIRED in this mode.",
    "rem",
    "rem  ASCII-only on purpose: .bat files are parsed using the",
    "rem  console code page, so non-ASCII text breaks the parser.",
    "rem",
    "rem  NOTE: this script puts no %VAR% inside an if( ... ) block,",
    "rem  because a path containing ( or ) breaks the cmd.exe parser.",
    "rem  All checks use if/errorlevel/goto instead.",
    "rem ===========================================================",
    "",
    'set "PORT=%~1"',
    'if "%PORT%"=="" set "PORT=8788"',
    'set "KEY=%~2"',
    'set "HERE=%~dp0"',
    'set "SCRIPT=%HERE%app\\wb_proxy.py"',
    "",
    'if not exist "%SCRIPT%" goto no_script',
    "",
    'set "PYEXE="',
    "",
    "rem ---- 1) bundled runtime (ships with the zip) ----",
    'if not exist "%HERE%python\\python.exe" goto try_path',
    '"%HERE%python\\python.exe" --version >nul 2>nul',
    "if errorlevel 1 goto try_path",
    'set "PYEXE=%HERE%python\\python.exe"',
    "goto run",
    "",
    ":try_path",
    "rem ---- 2) python on PATH ----",
    "python --version >nul 2>nul",
    "if errorlevel 1 goto try_py",
    'set "PYEXE=python"',
    "goto run",
    "",
    ":try_py",
    "rem ---- 3) py launcher ----",
    "py --version >nul 2>nul",
    "if errorlevel 1 goto no_python",
    'set "PYEXE=py"',
    "goto run",
    "",
    ":no_python",
    "echo [ERROR] No usable Python found.",
    "echo.",
    "echo Options:",
    "echo   1. Use the packaged zip, which already contains python\\",
    "echo   2. Install Python 3.9+ from https://www.python.org/downloads/",
    'echo      (tick "Add python.exe to PATH" during setup)',
    "echo.",
    "pause",
    "exit /b 1",
    "",
    ":no_script",
    "echo [ERROR] app\\wb_proxy.py not found.",
    "echo         expected: %SCRIPT%",
    "echo.",
    "pause",
    "exit /b 1",
    "",
    ":run",
    "echo ===========================================================",
    "echo   WorkBuddy proxy - LAN MODE",
    "echo.",
    "echo   Port %PORT% - your API address, dashboard link and API",
    "echo   key are printed below once the server is up.",
    "echo.",
    "echo   If other devices cannot connect, run allow-firewall.bat",
    "echo   once as administrator.",
    "echo.",
    "echo   Keep this window open. Closing it stops the server.",
    "echo ===========================================================",
    "echo.",
    "",
    "rem Pass --api-key only when the user supplied one; otherwise the gateway",
    "rem mints a random key on first run and prints it below.",
    'if "%KEY%"=="" goto run_nokey',
    '"%PYEXE%" "%SCRIPT%" --port %PORT% --lan --api-key %KEY%',
    "goto after_run",
    "",
    ":run_nokey",
    '"%PYEXE%" "%SCRIPT%" --port %PORT% --lan',
    "",
    ":after_run",
    "echo.",
    "echo [server exited]",
    "pause",
    "",
]

PLAIN = [
    "@echo off",
    "setlocal EnableExtensions",
    "rem ===========================================================",
    "rem  WorkBuddy international proxy - launcher",
    "rem  Usage: double-click, or  start-wb-proxy.bat [port]",
    "rem",
    "rem  ASCII-only on purpose: .bat files are read using the",
    "rem  console code page, so non-ASCII text breaks the parser.",
    "rem",
    "rem  NOTE: this script puts no %VAR% inside an if( ... ) block,",
    "rem  because a path containing ( or ) breaks the cmd.exe parser.",
    "rem  All checks use if/errorlevel/goto instead.",
    "rem ===========================================================",
    "",
    'set "PORT=%~1"',
    'if "%PORT%"=="" set "PORT=8788"',
    'set "HERE=%~dp0"',
    'set "SCRIPT=%HERE%app\\wb_proxy.py"',
    "",
    'if not exist "%SCRIPT%" goto no_script',
    "",
    'set "PYEXE="',
    "",
    "rem ---- 1) bundled runtime (ships with the zip) ----",
    'if not exist "%HERE%python\\python.exe" goto try_path',
    '"%HERE%python\\python.exe" --version >nul 2>nul',
    "if errorlevel 1 goto try_path",
    'set "PYEXE=%HERE%python\\python.exe"',
    "goto run",
    "",
    ":try_path",
    "rem ---- 2) python on PATH ----",
    "python --version >nul 2>nul",
    "if errorlevel 1 goto try_py",
    'set "PYEXE=python"',
    "goto run",
    "",
    ":try_py",
    "rem ---- 3) py launcher ----",
    "py --version >nul 2>nul",
    "if errorlevel 1 goto no_python",
    'set "PYEXE=py"',
    "goto run",
    "",
    ":no_python",
    "echo [ERROR] No usable Python found.",
    "echo.",
    "echo Options:",
    "echo   1. Use the packaged zip, which already contains python\\",
    "echo   2. Install Python 3.9+ from https://www.python.org/downloads/",
    'echo      (tick "Add python.exe to PATH" during setup)',
    "echo   3. Edit this file and set PYEXE to a full path, e.g.",
    'echo        set "PYEXE=C:\\Python312\\python.exe"',
    "echo.",
    "pause",
    "exit /b 1",
    "",
    ":no_script",
    "echo [ERROR] app\\wb_proxy.py not found.",
    "echo         expected: %SCRIPT%",
    "echo.",
    "pause",
    "exit /b 1",
    "",
    ":run",
    "echo ===========================================================",
    "echo   WorkBuddy proxy",
    "echo.",
    "echo   API      : http://127.0.0.1:%PORT%/v1",
    "echo   Dashboard: http://127.0.0.1:%PORT%/",
    "echo.",
    "echo   Python   : %PYEXE%",
    "echo.",
    "echo   Keep this window open. Closing it stops the server.",
    "echo   Press Ctrl+C to stop.",
    "echo ===========================================================",
    "echo.",
    "",
    '"%PYEXE%" "%SCRIPT%" --port %PORT%',
    "",
    "echo.",
    "echo [server exited]",
    "pause",
    "",
]


def dump(path, lines):
    body = "\r\n".join(lines).replace("\\'", "'")
    pathlib.Path(path).write_bytes(body.encode("ascii"))
    print("wrote", path, len(body), "bytes")


base = pathlib.Path(__file__).parent.parent  # the launchers live at the repository root
dump(base / "start-wb-proxy-lan.bat", LAN)
dump(base / "start-wb-proxy.bat", PLAIN)
